"""empty message

Revision ID: d29b4119b230
Revises: aa846e6a0ffa
Create Date: 2021-12-06 03:45:36.457086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29b4119b230'
down_revision = 'aa846e6a0ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gympost_user_id_fkey', 'gympost', type_='foreignkey')
    op.drop_column('gympost', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gympost', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('gympost_user_id_fkey', 'gympost', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
