"""empty message

Revision ID: 7db0237ae898
Revises: a819453e6ac2
Create Date: 2021-12-06 01:13:46.724893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db0237ae898'
down_revision = 'a819453e6ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gympost_name_key', 'gympost', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('gympost_name_key', 'gympost', ['name'])
    # ### end Alembic commands ###
