"""empty message

Revision ID: a819453e6ac2
Revises: 91ae76339876
Create Date: 2021-12-06 00:39:31.012573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a819453e6ac2'
down_revision = '91ae76339876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gympost_post_id_fkey', 'gympost', type_='foreignkey')
    op.drop_column('gympost', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gympost', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('gympost_post_id_fkey', 'gympost', 'user', ['post_id'], ['id'])
    # ### end Alembic commands ###
