"""empty message

Revision ID: aa846e6a0ffa
Revises: 7db0237ae898
Create Date: 2021-12-06 03:33:12.718427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa846e6a0ffa'
down_revision = '7db0237ae898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gympost', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gympost', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gympost', type_='foreignkey')
    op.drop_column('gympost', 'user_id')
    # ### end Alembic commands ###
